Trying to use a throw when invalid kv-pairs are detected
timiimit/UT4MasterServer pull request #111
Opened 2023-01-22 20:48 UTC by CounterRebel

2023-01-22 21:09 UTC, Saibamen commented on UT4MasterServer/Other/GameServerAttributesBsonSerializer.cs
> +				throw new FormatException("Invalid kv-pairs detected");
```suggestion
				throw new FormatException("Invalid KeyValue-pairs detected");
```

2023-01-22 21:10 UTC, Saibamen requested changes

2023-01-22 21:10 UTC, Saibamen commented on UT4MasterServer/Other/GameServerAttributesBsonSerializer.cs
> +				throw new FormatException("Invalid kv-pairs detected");
```suggestion
				throw new FormatException($"Invalid KeyValue-pairs detected. Key: {key}");
```

2023-01-22 22:42 UTC, timiimit commented
What is the reasoning for why throwing would be better?

2023-01-25 12:44 UTC, timiimit commented
No valid reason provided for added changes.

2023-01-25 12:44 UTC, closed without merging