Add test for confirming desired elo funcionality
timiimit/UT4MasterServer pull request #180
Opened 2023-02-07 15:59 UTC by timiimit

2023-02-07 16:02 UTC, Saibamen requested changes

2023-02-07 16:22 UTC, timiimit commented on .Tests/XUnit.Tests/EloTest.cs
> +	[InlineData(100, 5, 1000)]
there's only so many possible tests. cant really think of any edge cases other than 1v1 match.

2023-02-07 18:59 UTC, Saibamen commented on .Tests/XUnit.Tests/EloTest.cs
> +	[InlineData(100, 5, 1000)]
So please add 1-2 more test and 1vs1 match. Otherwise, this test is not a `[Theory]`, but `[Fact]`

2023-02-07 21:19 UTC, timiimit commented on .Tests/XUnit.Tests/EloTest.cs
> +	[InlineData(100, 5, 1000)]
I did add 7 cases in total... including a 1vs1

2023-02-08 11:14 UTC, Saibamen commented
Related: #138

2023-02-08 11:16 UTC, Saibamen approved these changes

2023-02-08 11:17 UTC, Saibamen commented on .Tests/XUnit.Tests/EloTest.cs
> +		double expectedAvg = players.Select(x => x.ApproxSkillRating).Average();
```suggestion
		double avg = players.Select(x => x.Rating).Average();
		double expectedAvg = players.Select(x => x.ApproxSkillRating).Average();
```

2023-02-08 11:17 UTC, merged