ELO fixes
timiimit/UT4MasterServer pull request #181
Opened 2023-02-07 19:06 UTC by belmirp

- Fixed DM ELO calculation
- Excluded accounts with empty account ID from calculation
- Added logs for future monitoring

Related: [#138](https://github.com/timiimit/UT4MasterServer/issues/138)

2023-02-07 19:26 UTC, Saibamen requested changes
We already have timestamp in logs. See our template logs template: https://github.com/timiimit/UT4MasterServer/blob/master/UT4MasterServer/Configuration/InternalLoggerConfiguration.cs#L10

2023-02-07 20:44 UTC, Saibamen approved these changes

2023-02-07 20:44 UTC, merged

2023-02-07 23:06 UTC, timiimit reviewed
LogInformation will not be visible in production. I don't think logging every request makes sense. I was expecting you to only log the cases when we detect unexpected content.

2023-02-08 11:21 UTC, Saibamen commented
> LogInformation will not be visible in production

For clarity: you can configure to not log info from Microsoft, but log every other or log info for specific controller/services etc

https://github.com/timiimit/UT4MasterServer/blob/master/UT4MasterServer/appsettings.json#L23