Fix gameserver listing
timiimit/UT4MasterServer pull request #45
Opened 2023-01-03 17:33 UTC by timiimit

This PR makes listing hubs and servers within hubs work.

2023-01-03 18:33 UTC, Saibamen commented on UT4MasterServer/Controllers/UnrealTournamentMatchmakingController.cs
> +	/// <summary>
```suggestion
	/// <summary>
```

2023-01-03 18:33 UTC, Saibamen commented on UT4MasterServer/Controllers/UnrealTournamentMatchmakingController.cs
> +			// allow any third-party project to easily access hub list without any authentication
Maybe add information log?

2023-01-03 19:22 UTC, timiimit commented on UT4MasterServer/Controllers/UnrealTournamentMatchmakingController.cs
> +			// allow any third-party project to easily access hub list without any authentication
Done

2023-01-04 02:18 UTC, Saibamen requested changes

2023-01-04 02:18 UTC, Saibamen commented on UT4MasterServer/Program.cs
> +	private static DateTime startupTime = DateTime.Now;
```suggestion
	private static DateTime startupTime = DateTime.UtcNow;
```

2023-01-04 02:19 UTC, Saibamen requested changes

2023-01-04 02:19 UTC, Saibamen commented on UT4MasterServer/Program.cs
> +	public static DateTime StartupTime => startupTime;
UTC
```suggestion
	public static DateTime StartupTime { get; } = DateTime.UtcNow;
```

2023-01-04 08:01 UTC, merged